name: test
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [closed, synchronize]
jobs:
  printInputsPush:
    runs-on: ubuntu-latest
    # if: ${{ github.event.action == 'push' }}
    steps:
    - run: |
        echo "action is ${{github.event.action}}"
        echo "GITHUB_REF  is ${GITHUB_REF}"
        echo "GITHUB_HEAD_REF is ${GITHUB_HEAD_REF}"
        echo "YAY"
        echo "HI"
