name: test 
on:
  workflow_dispatch:
    inputs:
      hi:
        description: 'fil me in you have to '
        required: true
        default: 'noooo'
      bool:
        description: 'type anything in here'
  pull_request:
    types: [synchronize]
