name: test 
on: 
  push:
  pull_request:
    types: [closed, synchronize]
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${GITHUB_REF#refs/heads/}"
        echo "${GITHUB_HEAD_REF}"
        echo "YAY"
        echo "HI"
